using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TerminalConnector
{
	internal class MashreqErrorData
	{
		private static readonly Dictionary<string, string> errorCodes = new Dictionary<string, string>
		{
		{ "E000", "No Error" },
		{ "E001", "Terminal Not Initialized" },
		{ "E002", "Batch Full" },
		{ "E003", "Card Not removed from Card Reader" },
		{ "E004", "Incorrect Amount Received" },
		{ "E005", "Invalid Message Type Received" },
		{ "E006", "Out Of Paper Roll" },
		{ "E007", "XML Format Error" },
		{ "E008", "Expired Card" },
		{ "E009", "Card Not Supported" },
		{ "E010", "Transaction being completed against wrong transaction type" },
		{ "E011", "Low Battery" },
		{ "E012", "Data Base Error Exception" },
		{ "E013", "Invalid Track" },
		{ "E014", "Customer Cancellation" },
		{ "E015", "Card Reader Time Out" },
		{ "E016", "Pin Timeout" },
		{ "E017", "Invalid Expiry" },
		{ "E018", "Card not supported (Bin Not found)" },
		{ "E019", "AID Not Supported" },
		{ "E020", "Wrong Password (Need to check)" },
		{ "E021", "Chip Read Error" },
		{ "E022", "Service Code Check Error" },
		{ "E023", "Connection Error" },
		{ "E024", "Send Exception" },
		{ "E025", "Receive Exception" },
		{ "E026", "Invalid Receipt Number" },
		{ "E027", "Transaction already voided" },
		{ "E028", "Transaction not found" },
		{ "E029", "Wrong N Digits" },
		{ "E030", "Maximum Amount Digits Exceeded" },
		{ "E031", "ATM Only Exception" },
		{ "E032", "Amount Not Matching" },
		{ "E033", "Disk Exception (Remote Program Download)" },
		{ "E034", "Decompression Exception" },
		{ "E035", "Reversal Incomplete" },
		{ "E036", "Card Removed during Transaction" },
		{ "E037", "Response parse Error" },
		{ "E038", "Reversal Send Exception" },
		{ "E039", "Reversal Receive Exception" },
		{ "E040", "Crypto Error" },
		{ "E041", "Batch Empty" },
		{ "E042", "Swipe Card Only" },
		{ "E043", "Run Time Exception" },
		{ "E044", "Host/EMV Response Code Error" },
		{ "E045", "Date Time Sync Error" },
		{ "E046", "ECR DB Error" },
		{ "E053", "Transaction not permitted at the terminal permissions/ Access denied" },
		{ "E055", "ICC Exception error" },
		{ "E057", "Permission Exception" },
		{ "E058", "Exceed Max Amount Exception" },
		{ "E059", "Operation Cancellation" },
		{ "E063", "Miss Match Data" },
		{ "E064", "Sim Configuration Error/ Sim Slot Exception" },
		{ "E065", "Gprs Restart Exception" },
		{ "E067", "Call last transaction status" },
		{ "E069", "Mref value is Mismatch" },
		{ "E070", "Mref not Valid" },
		{ "E071", "EMV Processing Error" },
		{ "E073", "Connection Interface Exhausted" },
		{ "E074", "EDW: Limit of transaction count per Terminal ID in 24 hours exceeded" },
		{ "E075", "EDW: Limit of transaction count per Terminal ID in 1 hour exceeded" },
		{ "E076", "EDW: Max transaction amount exceeded" },
		{ "E081", "Declined" },
		{ "E082", "Read card data Fail" },
		{ "E083", "Detect card Failed" },
		{ "E100", "SAM Authentication error" },
		{ "E101", "Invalid Maximum NOL Amount for Card type" },
		{ "E102", "Card Mismatch- Another NOL card tapped for Re-Tap" },
		{ "E103", "Blocked Card - NOL" },
		{ "E104", "Disabled Card - NOL" },
		{ "E105", "Nol Card Retired" },
		{ "E106", "Nol Card Detection error" },
		{ "E107", "Transaction Amount greater than available amount in card" },
		{ "E108", "SAM Detection Error" },
		{ "E109", "Invalid card – Card type not as per RTA" },
		{ "E110", "Invalid card status" },
		{ "E111", "Invalid Epurse status" },
		{ "E112", "Application TSN Limit error" },
		{ "E113", "Tpurse TSN Limit error" },
		{ "E114", "Invalid Amount" },
		{ "E115", "FAT Serial Number Limit error" },
		{ "E116", "Invalid Epurse Balance" },
		{ "E117", "NOL read error" },
		{ "E118", "NOL write error" },
		{ "E119", "Update NOL card error" },
		{ "E120", "NOL card authentication error" },
		{ "E121", "NOL Application selection error" },
		{ "E122", "SAM Key KCV Mismatch" },
		{ "E123", "Invalid URN" },
		{ "E124", "Invalid OTP" },
		{ "E125", "Application Crash or terminated" },
		{ "E126", "General Error" },
		{ "E127", "Bank Key not Injected" },
		{ "E128", "Transaction not allowed" },
		{ "E129", "Transaction syncing to host (When terminal sending any advice or reversal)" },
		{ "E130", "Not enough memory to perform the transaction" },
		{ "E131", "Please perform last transaction" },
		{ "E06",  "No response from EFT device [error generated from DLL]" },
		{ "E180", "No device detected" },
		{ "E181", "USB Re-connecting" },
		{ "E182", "USB Disconnected" },
		{ "E183", "Access denied to COM Port" }
		};

		public string GetErrorDescription(string errorCode)
		{
			return errorCodes.TryGetValue(errorCode, out string description) ? description : "Unknown Error Code";
		}


        private static readonly Dictionary<string, string> commandMessages = new Dictionary<string, string>
		{
		    { "001", "Enter card Displayed" },
		    { "002", "Card Inserted" },
		    { "003", "FallBack happened" },
		    { "004", "Display Swipe Card" },
		    { "005", "Card Swiped" },
		    { "006", "Enter PIN" },
		    { "007", "PIN Entered" },
		    { "008", "Online Processing" },
		    { "009", "Response received from the host" },
		    { "010", "Printing of Receipt" },
		    { "011", "Remove Card displayed" },
		    { "012", "Card Removed" },
		    { "013", "Transaction Successful" },
		    { "014", "Transaction Failed" },
		    { "015", "Transaction Being Reversed" },
		    { "016", "Waiting for Logo" },
		    { "017", "Displaying EPP Menu" },
		    { "018", "Sending EPP Inq" },
		    { "019", "EPP Inq Response Received from Host" },
		    { "020", "Print EPP Plan" },
		    { "021", "Displaying Salaam Menu" },
		    { "022", "Sending Salaam Inq" },
		    { "023", "Salaam Inq Received from Host" },
		    { "024", "Print Salam Inq" },
		    { "025", "DCC Rate Look up" },
		    { "026", "DCC Offer Screen" },
		    { "027", "DCC OPT IN" },
		    { "028", "DCC OPT OUT" },
		    { "029", "DCC Selection Cancelled" },
		    { "030", "DCC Selection Wait" },
		    { "031", "Fallback Contactless to Contact" },
		    { "032", "Out of Paper, replace paper roll" },
		    { "033", "Enter Tip Amount" },
		    { "034", "Display New Amount" },
		    { "035", "Enter Original Amount" },
		    { "036", "Send Auth Completion Verification" },
		    { "037", "Display Auth verification screen" },
		    { "038", "Auth Completion Amount entered" },
		    { "039", "Enter Auth Code" },
		    { "040", "Purchase Transaction to Auto EPP" },
		    { "041", "Display Auto EPP (if the card or amount is eligible for EPP)" },
		    { "042", "PIN ByPass Entered" },
		    { "043", "Manual Entry" },
		    { "044", "Contactless (Tap card)" },
		    { "045", "Max Tip Exceeded" },
		    { "046", "Terminal Removed from Base" },
		    { "047", "Check Last Txn Status" },
		    { "048", "Enter MREF" },
		    { "049", "MREF Entered" },
		    { "052", "GPRS Communication" },
		    { "053", "Ethernet Communication" },
		    { "055", "Serial Communication" },
		    { "056", "Scan QR" },
		    { "057", "EDW Customer app notification received" },
		    { "058", "Wallet Txn history query/Get Tran status" },
		    { "059", "Wallet Response timeout" },
		    { "060", "Enter Reference number" },
		    { "061", "Enter OTP" },
		    { "062", "OTP Entered" }
		};


        public string GetCommandDescription(string errorCode)
        {
            return commandMessages.TryGetValue(errorCode, out string description) ? description : "Unknown Error Code";
        }

    }



}
